Remove Growthcraft
Causing this crash:

16:13:38 [SEVERE] The following problems were captured during this phase
16:13:38 [SEVERE] Caught exception from ExtraUtilities
java.lang.NoClassDefFoundError: net/minecraft/client/renderer/tileentity/TileEntitySpecialRenderer
	at growthcraft.cellar.block.BlockFermentBarrel.func_71857_b(BlockFermentBarrel.java:355)
	at extrautils.tileentity.enderquarry.BlockBreakingRegistry.setupBreaking(BlockBreakingRegistry.java:69)
	at extrautils.ExtraUtils.postInit(ExtraUtils.java:1800)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:540)
	at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
	at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:313)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
	at com.google.common.eventbus.EventBus.post(EventBus.java:267)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:200)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:180)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
	at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:313)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
	at com.google.common.eventbus.EventBus.post(EventBus.java:267)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:111)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:692)
	at cpw.mods.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:102)
	at cpw.mods.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:370)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:180)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:637)
	at net.minecraft.server.ThreadMinecraftServer.run(SourceFile:583)
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.renderer.tileentity.TileEntitySpecialRenderer
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:186)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 34 more
Caused by: java.lang.NullPointerException
16:13:38 [SEVERE] cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: net/minecraft/client/renderer/tileentity/TileEntitySpecialRenderer
16:13:38 [SEVERE] 	at cpw.mods.fml.common.LoadController.transition(LoadController.java:155)
16:13:38 [SEVERE] 	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:693)
16:13:38 [SEVERE] 	at cpw.mods.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:102)
16:13:38 [SEVERE] 	at cpw.mods.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:370)
16:13:38 [SEVERE] 	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:180)
16:13:38 [SEVERE] 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:637)
16:13:38 [SEVERE] 	at net.minecraft.server.ThreadMinecraftServer.run(SourceFile:583)
16:13:38 [SEVERE] Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/renderer/tileentity/TileEntitySpecialRenderer
16:13:38 [SEVERE] 	at growthcraft.cellar.block.BlockFermentBarrel.func_71857_b(BlockFermentBarrel.java:355)
16:13:38 [SEVERE] 	at extrautils.tileentity.enderquarry.BlockBreakingRegistry.setupBreaking(BlockBreakingRegistry.java:69)
16:13:38 [SEVERE] 	at extrautils.ExtraUtils.postInit(ExtraUtils.java:1800)
16:13:38 [SEVERE] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
16:13:38 [SEVERE] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
16:13:38 [SEVERE] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
16:13:38 [SEVERE] 	at java.lang.reflect.Method.invoke(Method.java:498)
16:13:38 [SEVERE] 	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:540)
16:13:38 [SEVERE] 	at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
16:13:38 [SEVERE] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
16:13:38 [SEVERE] 	at java.lang.reflect.Method.invoke(Method.java:498)
16:13:38 [SEVERE] 	at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
16:13:38 [SEVERE] 	at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
16:13:38 [SEVERE] 	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:313)
16:13:38 [SEVERE] 	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
16:13:38 [SEVERE] 	at com.google.common.eventbus.EventBus.post(EventBus.java:267)
16:13:38 [SEVERE] 	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:200)
16:13:38 [SEVERE] 	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:180)
16:13:38 [SEVERE] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
16:13:38 [SEVERE] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
16:13:38 [SEVERE] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
16:13:38 [SEVERE] 	at java.lang.reflect.Method.invoke(Method.java:498)
16:13:38 [SEVERE] 	at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
16:13:38 [SEVERE] 	at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
16:13:38 [SEVERE] 	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:313)
16:13:38 [SEVERE] 	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
16:13:38 [SEVERE] 	at com.google.common.eventbus.EventBus.post(EventBus.java:267)
16:13:38 [SEVERE] 	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:111)
16:13:38 [SEVERE] 	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:692)
16:13:38 [SEVERE] 	... 5 more
16:13:38 [SEVERE] Caused by: java.lang.ClassNotFoundException: net.minecraft.client.renderer.tileentity.TileEntitySpecialRenderer
16:13:38 [SEVERE] 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:186)
16:13:38 [SEVERE] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
16:13:38 [SEVERE] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
16:13:38 [SEVERE] 	... 34 more
16:13:38 [SEVERE] Caused by: java.lang.NullPointerException
16:13:38 [SEVERE] Encountered an unexpected exception LoaderException
cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: net/minecraft/client/renderer/tileentity/TileEntitySpecialRenderer
	at cpw.mods.fml.common.LoadController.transition(LoadController.java:155)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:693)
	at cpw.mods.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:102)
	at cpw.mods.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:370)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:180)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:637)
	at net.minecraft.server.ThreadMinecraftServer.run(SourceFile:583)
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/renderer/tileentity/TileEntitySpecialRenderer
	at growthcraft.cellar.block.BlockFermentBarrel.func_71857_b(BlockFermentBarrel.java:355)
	at extrautils.tileentity.enderquarry.BlockBreakingRegistry.setupBreaking(BlockBreakingRegistry.java:69)
	at extrautils.ExtraUtils.postInit(ExtraUtils.java:1800)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:540)
	at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
	at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:313)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
	at com.google.common.eventbus.EventBus.post(EventBus.java:267)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:200)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:180)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
	at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:313)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
	at com.google.common.eventbus.EventBus.post(EventBus.java:267)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:111)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:692)
	... 5 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.renderer.tileentity.TileEntitySpecialRenderer
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:186)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 34 more
Caused by: java.lang.NullPointerException